# Generated by Django 3.0.7 on 2020-10-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='TopCategory',
        ),
    ]
