# Generated by Django 3.0.7 on 2020-10-09 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201009_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.TopCategory')),
            ],
            options={
                'db_table': 'altcategories',
                'ordering': ['-created_at'],
            },
        ),
    ]
